// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.0--rc2
// source: proto/proteccion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProtectorClient is the client API for Protector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProtectorClient interface {
	Proteger(ctx context.Context, in *SolicitudProteger, opts ...grpc.CallOption) (*RespuestaProteger, error)
}

type protectorClient struct {
	cc grpc.ClientConnInterface
}

func NewProtectorClient(cc grpc.ClientConnInterface) ProtectorClient {
	return &protectorClient{cc}
}

func (c *protectorClient) Proteger(ctx context.Context, in *SolicitudProteger, opts ...grpc.CallOption) (*RespuestaProteger, error) {
	out := new(RespuestaProteger)
	err := c.cc.Invoke(ctx, "/proto.Protector/Proteger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProtectorServer is the server API for Protector service.
// All implementations must embed UnimplementedProtectorServer
// for forward compatibility
type ProtectorServer interface {
	Proteger(context.Context, *SolicitudProteger) (*RespuestaProteger, error)
	mustEmbedUnimplementedProtectorServer()
}

// UnimplementedProtectorServer must be embedded to have forward compatible implementations.
type UnimplementedProtectorServer struct {
}

func (UnimplementedProtectorServer) Proteger(context.Context, *SolicitudProteger) (*RespuestaProteger, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Proteger not implemented")
}
func (UnimplementedProtectorServer) mustEmbedUnimplementedProtectorServer() {}

// UnsafeProtectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProtectorServer will
// result in compilation errors.
type UnsafeProtectorServer interface {
	mustEmbedUnimplementedProtectorServer()
}

func RegisterProtectorServer(s grpc.ServiceRegistrar, srv ProtectorServer) {
	s.RegisterService(&Protector_ServiceDesc, srv)
}

func _Protector_Proteger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolicitudProteger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProtectorServer).Proteger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Protector/Proteger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProtectorServer).Proteger(ctx, req.(*SolicitudProteger))
	}
	return interceptor(ctx, in, info, handler)
}

// Protector_ServiceDesc is the grpc.ServiceDesc for Protector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Protector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Protector",
	HandlerType: (*ProtectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Proteger",
			Handler:    _Protector_Proteger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proteccion.proto",
}
